### DISCUSSION TITLE
Tutorial

### DISCUSSION THREAD

**Discussion by PrzemekSkw** [coach1988/IPTV-Solution#1] [General]
Hello, is possible to add some tutorial because I don't know how to start.
![image](https://user-images.githubusercontent.com/25219988/228339325-e3fa9fe3-4c2b-47a8-bee1-61ea27e445f3.png)

Regards.

**Comment by coach1988** [comment]
Hi @PrzemekSkw ,

sorry, I must have missed the notification for this:-/ The main steps are as following (assuming you're working with a new, unknown playlist):

1. Go to the upstream user agent strings and define something; You can call it e.g. "Browser" with a value of "Mozilla/5.0 (Linux; Android 12; SM-S906N Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.119 Mobile Safari/537.36", which should mimic a Firefox browser (this is necessary, as some providers accept only specific UA strings)
2. Go to the upstream proxy servers and enter your proxy's data; These are defined in your .env/docker-compose files; The internal URL and port are used by the management process to interact with the proxy, the external information is what will end up in your proxified m3u that your clients will connect to; While this might be the same depending on the network layout, it is often required to enter different values, e.g. when utilizing reverse proxies
3. Go to upstream playlists and enter the information for your playlist; Choose a name and set an update interval (it does NOT auto-update the playlist; Instead it will check if at least this amount of hours has passed since the last update and will redownload the file accordingly on-demand). Select the user agent to use to download the file from your provider (won't be used if it's a local file) and save everything for now
4. In the upstream playlists overview, select your playlist and choose "Download, filter and import upstream playlist(s)" from the dropdown menu on top; This might take a moment
5. Once the initial import has finished, go to the IPTV channel groups, which should be populated now; Click on "Get group list" in the top right and copy the output somewhere
6. Go to the downstream playlists and define a playlist for your clients; The streaming proxy you select will end up in the m3u; Copy & paste all groups you want to include into the channel groups field; If these contain specific channels you don't want to include, you can enter strings to filter out in the channel filters field, which will filter out all channels that start with/end with/contain/exactly match these strings
7. You're ready=) Open the URL "http://localhost:8088/manager/get/playlist/name" (replace the URI handler, hostname, and port to match your management interface and replace name with the downstream playlist's name), that should download the playlist
8. Optional: To speed up the channel import in the future, you can go back to the upstream playlists and copy & paste all the groups from step 5 you don't want to import in the filtered groups field; I recommend going to the iptv channels + iptv channel groups and purging both lists (button on the top right) to get rid of unwanted entries and then going to the upstream playlists to import them again, otherwise you might end up with stale entries if you filter them out in subsequent imports
9. Optionally define EPG's or disable individual channels/groups, which should filter them out globally

I hope this helps and doesn't come too late=)

**Reply by PrzemekSkw** [reply]
Thank You very much for that guide :)

**Reply by DjLaz** [reply]
hello
you think there is a simple way to update the playlist faster ? i get many error django saying (database is locked) 
or my playlist is too big and iptv manager can't handle it ?

**Reply by coach1988** [reply]
Hi @DjLaz,

I've just pushed a huge update that addresses basically every aspect; However, the main issue with locked databases will still occur, as it happens because you're trying to interact with db tables that are in use during the import. 
There might be a way to disable this batch-processing/paging/transactional approach, but that would lead to more (because individual) database calls, making the import even slower.

PS: The easiest way to speed up the process is to define groups to filter out; The initial import will still take long, but once the list is populated, it will skip everything that's unwanted (especially helpful with long VoD and 24/7 lists)

**Comment by jimmisavage** [comment]
I have followed your instrI have followed your instructions to the letter and I think I understand what's happening but I can't download the .m3u file... each time I try, it just updates the playlist:

End of an update the log gives:
```
2023-12-12 10:05:34 [INFO]: DOWNSTREAM: Generating playlist stoogle
2023-12-12 10:06:14 [INFO]: DOWNSTREAM stoogle: Filter mode: A
2023-12-12 10:06:14 [INFO]: DOWNSTREAM: Saved as /app/staticfiles/playlists/downstream/c3Rvb2dsZQ==.m3u
2023-12-12 10:06:14 [INFO]: views.py: /manager/get/playlist/stoogle ---> Transferred downstream playlist stoogle
```

Then when I go to http://localhost:8088/manager/get/playlist/stoogle it just refreshes the playlist again:
```
2023-12-12 10:07:52 [INFO]: DOWNSTREAM: Updating/importing upstream playlist StoogleTV
2023-12-12 10:07:52 [INFO]: UPSTREAM StoogleTV: Upstream playlist update requested
2023-12-12 10:07:52 [INFO]: UPSTREAM StoogleTV: File already exists, checking if download is required...
2023-12-12 10:07:52 [INFO]: UPSTREAM StoogleTV: File is 14.44 hours old, download skipped...
2023-12-12 10:07:52 [INFO]: UPSTREAM StoogleTV: Filtering channels
2023-12-12 10:07:53 [INFO]: UPSTREAM StoogleTV: Filtering out group
```

I also have a question about the docker-compose file. Should I change the reporting URL and Internal Proxy URL to IPTV-Manager and IPTV-Proxy (and do I need to include "")? Should I be uncommenting anything else?

```
version: "3"

services:
  manager:
    build:
      context: ./manager/
    container_name: "IPTV-Manager"
    image: iptv-manager
    network_mode: "container:gluetun"
    volumes:
      - ./volumes/static/:/app/staticfiles/
      - ./volumes/database/:/app/database/
    environment:
    # - ALLOWED_HOSTS: "['*']"    
    # - TIME_ZONE=UTC
    # - DJANGO_SUPERUSER_USERNAME=admin
    # - DJANGO_SUPERUSER_EMAIL=[admin@admin.com](mailto:admin@admin.com)
    # - DJANGO_SUPERUSER_PASSWORD=password
      - SECRET_KEY=secret
    # - DEBUG=True
    # - DEBUGLEVEL=DEBUG
    # - SOCKET_ADDRESS="0.0.0.0"
      - MANAGEMENT_URL=https://mysite/
    # - INTERNAL_MANAGEMENT_PORT=8088
    # - EXTERNAL_MANAGEMENT_PORT=8088
    # - INTERNAL_TIMEOUT=1
    # - ALLOWED_URL_SCHEMES="['http', 'https', 'mmsh', 'mmst', 'mmsu', 'mms', 'rtmp', 'rtsp']"
    # - BLOCKED_PATH_TYPES="['.m3u', '.m3u8', '.mpd']"
    # - BLOCKED_URL_REGEXS="['output=playlist.m3u[8]?', '[www.youtube.com/'](http://www.youtube.com/')]"
    # - USER_AGENT_STRING="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36)"
    # - PLAYLIST_TIMEOUT=120
    # - EPG_TIMEOUT=120
    # - ICON_TIMEOUT=15
    restart: unless-stopped
      
  proxy:
    build:
      context: ./proxy/
    container_name: "IPTV-Proxy"
    image: iptv-proxy
    ports:
      - 8089:8089/tcp
    environment:
    # - DEBUG=True
    # - SOCKET_ADDRESS=0.0.0.0
      - REPORTING_URL=http://manager/ # Match your management container's name if running in the same stack
    # - REPORTING_PORT=8088
    # - REPORTING_TIMEOUT=5
    # - PROXY_NAME=IPTV-Proxy
      - INTERNAL_PROXY_URL=http://proxy/ # Match your proxy container's name if running in the same stack
    # - INTERNAL_PROXY_PORT=8089
    # - EXTERNAL_PROXY_URL=http://localhost/
    # - EXTERNAL_PROXY_PORT=8089
    # - USER_AGENT_STRING=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36)
    # - STREAM_TIMEOUT=15
    links:
      - manager
    restart: unless-stopped
```


Again, sorry to take your time! I feel like I'm so close, I don't want to give up! 

Many thanks
Stuart
