### ISSUE TITLE
Cannot download m3u file

### ISSUE THREAD

**Issue by jimmisavage** [coach1988/IPTV-Solution#7]
I have followed your instructions to the letter and I think I understand what's happening but I can't download the .m3u file... each time I try, it just updates the playlist:

End of an update the log gives:
```
2023-12-12 10:05:34 [INFO]: DOWNSTREAM: Generating playlist stoogle
2023-12-12 10:06:14 [INFO]: DOWNSTREAM stoogle: Filter mode: A
2023-12-12 10:06:14 [INFO]: DOWNSTREAM: Saved as /app/staticfiles/playlists/downstream/c3Rvb2dsZQ==.m3u
2023-12-12 10:06:14 [INFO]: views.py: /manager/get/playlist/stoogle ---> Transferred downstream playlist stoogle
```

Then when I go to http://localhost:8088/manager/get/playlist/stoogle it just refreshes the playlist again:
```
2023-12-12 10:07:52 [INFO]: DOWNSTREAM: Updating/importing upstream playlist StoogleTV
2023-12-12 10:07:52 [INFO]: UPSTREAM StoogleTV: Upstream playlist update requested
2023-12-12 10:07:52 [INFO]: UPSTREAM StoogleTV: File already exists, checking if download is required...
2023-12-12 10:07:52 [INFO]: UPSTREAM StoogleTV: File is 14.44 hours old, download skipped...
2023-12-12 10:07:52 [INFO]: UPSTREAM StoogleTV: Filtering channels
2023-12-12 10:07:53 [INFO]: UPSTREAM StoogleTV: Filtering out group
```

I also have a question about the docker-compose file. Should I change the reporting URL and Internal Proxy URL to IPTV-Manager and IPTV-Proxy (and do I need to include "")? Should I be uncommenting anything else?

```
version: "3"

services:
  manager:
    build:
      context: ./manager/
    container_name: "IPTV-Manager"
    image: iptv-manager
    network_mode: "container:gluetun"
    volumes:
      - ./volumes/static/:/app/staticfiles/
      - ./volumes/database/:/app/database/
    environment:
    # - ALLOWED_HOSTS: "['*']"    
    # - TIME_ZONE=UTC
    # - DJANGO_SUPERUSER_USERNAME=admin
    # - DJANGO_SUPERUSER_EMAIL=[admin@admin.com](mailto:admin@admin.com)
    # - DJANGO_SUPERUSER_PASSWORD=password
      - SECRET_KEY=secret
    # - DEBUG=True
    # - DEBUGLEVEL=DEBUG
    # - SOCKET_ADDRESS="0.0.0.0"
      - MANAGEMENT_URL=https://mysite/
    # - INTERNAL_MANAGEMENT_PORT=8088
    # - EXTERNAL_MANAGEMENT_PORT=8088
    # - INTERNAL_TIMEOUT=1
    # - ALLOWED_URL_SCHEMES="['http', 'https', 'mmsh', 'mmst', 'mmsu', 'mms', 'rtmp', 'rtsp']"
    # - BLOCKED_PATH_TYPES="['.m3u', '.m3u8', '.mpd']"
    # - BLOCKED_URL_REGEXS="['output=playlist.m3u[8]?', '[www.youtube.com/'](http://www.youtube.com/')]"
    # - USER_AGENT_STRING="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36)"
    # - PLAYLIST_TIMEOUT=120
    # - EPG_TIMEOUT=120
    # - ICON_TIMEOUT=15
    restart: unless-stopped
      
  proxy:
    build:
      context: ./proxy/
    container_name: "IPTV-Proxy"
    image: iptv-proxy
    ports:
      - 8089:8089/tcp
    environment:
    # - DEBUG=True
    # - SOCKET_ADDRESS=0.0.0.0
      - REPORTING_URL=http://manager/ # Match your management container's name if running in the same stack
    # - REPORTING_PORT=8088
    # - REPORTING_TIMEOUT=5
    # - PROXY_NAME=IPTV-Proxy
      - INTERNAL_PROXY_URL=http://proxy/ # Match your proxy container's name if running in the same stack
    # - INTERNAL_PROXY_PORT=8089
    # - EXTERNAL_PROXY_URL=http://localhost/
    # - EXTERNAL_PROXY_PORT=8089
    # - USER_AGENT_STRING=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36)
    # - STREAM_TIMEOUT=15
    links:
      - manager
    restart: unless-stopped
```

Again, sorry to take your time! I feel like I'm so close, I don't want to give up! 

Many thanks
Stuart
